site_name: Programación ASIR en Java
site_description: Materiales del curso de ASIR en Java
repo_url: https://github.com/macapillaherrero/Programacion
repo_name: macapillaherrero/programacion
theme:
  name: material
  language: es
  logo: ./assets/images/camp.png
  icon: fontawesome/brands/mastodon
  hljs_languages:
    - python
    - java
    - c
  features:
    - navigation.top
    - optimize
    - content.code.copy
    - navigation.footer
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Modo oscuro
      primary: teal
      accent: teal 

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
      primary: teal
      accent: teal
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences